---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-meshcentral
  namespace: extras
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp6s18",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.1.121/24",
            "gateway": "192.168.1.1"
          }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-forge-network
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "vlan",
      "master": "enp6s19",
      "mode": "bridge",
      "vlanId": 2,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.10.121/25",
            "gateway": "192.168.10.1"
          }
        ]
      }
    }'