---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hl.brhd.io
  namespace:  kube-dashboard
spec:
  endpoints:
    - dnsName: hl.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
