---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-home-assistant
  namespace: smart-home
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp6s18.1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.12.70/25",
            "gateway": "192.168.12.1"
          }
        ]
      }
    }'
