---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: invidious-companion-cache
  namespace: privacy
  labels:
    app.kubernetes.io/name: invidious
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 1G
