---
# Superuser creds that can be reused for multiple CNPG cluster deployments
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-default-secret
  namespace: default
spec:
  encryptedData:
    password: AgBAZEvTGqEHdjnWGZcKybhLwPBSSa9y5s3wB7sIiUaC5XkWVwi7Nw3QLFBfUWQV14kquo4iVRfBK0q/IQ4MXDBqncNGU7x8HvmmdgqoW6Wl4OPyPHcG/Yta7gFi3U9EoQMc6IB9euCjlWeIH52QFjsadsy98BkE7hyC5R8cUHoAr33sLG7PpkXKungT6jt9PSPuH5bVVkvTsKili4Lkw9Ny8qfaD38BvDAx6onMXc5tHBlQaVDwQb26imfH4O3pd2TTEdIKSwmHjtvopLZfVgCgS+sy/hZFyRX45F2psrE1QdHVFhRETEa7dHWdeCK4XflJr3cYhr7Risnu1wwiwQC96VZC712U9U92DOkV+GsPYrEh3beGCoC5eSf3HbJoVq03ZsAtJWPLOBjZVTCLGw5yV4K/qmHCtPE7pyCw/5Z2Wmu6xIgu7aevX9W1BPCoKLvwBrzzrZdAUqtM3bLfVs4JGmELxOKpYAV59boDyjRNWmXVRu//6l9mS1vNHapwwQvB3H/w1LiayzQqI6J0MAqbqrPFw8mijgqGprjY+mrmeFnC7ooqWAygZwPaAbpKcT2vTI+R6lDiHSMSXaBxr3OZILq7EpO11O8ra+kpBlvICNH0WgUZtUDXF8e40GPn8RedQSMUH68FpEEHvfGgJRpV3GXoln9Cd5k+3YufRLVgplJqZWJbQwZsbxuSr2jEvMO/PzjVpSOEotwmu+hpJwKCoQ8g/PYB3JqXbXlk
    username: AgCp2HlBti6HwjdLkUixGAVre6EvtoC3tz7DLd34uMYbK2Sm+z2ZEhEYr2jV6AWtk6FcOjYBbwxRkgsLlM/MjTF/6W62jzKhWS/KG/78lXVISPHm1TlgwDPMyuWEZhgMpboQMnrM/7qoWt2uq6t6B04VGdMGD6YIDM9C31wimB8h3v8rwTH4Ez7jDp/Z1517V+yMaVL3J4geUpOZjB7AWUEzsjz7ITRjfkICGk+pId1ZCOQPAw+9xnmi+58/kA6iCxUabtyc+Jj/M7XVi7LXEHTXzlgWCla2dRz2gKF79DnYNRXsyKvbBr06J3ZLa4QcJktDpiUmme3lQMBZBc1zW49/An8fi2Hwlx3NK1xsCcR9TkjI6YyBpK/0N3yYhXkoGS1DfGGFT8aT4kqrqSvgZDS6k6QmIujLmoVLkn2MwgTH7qn8P7YVPbFKVehiGouROrZqAdqb28eurLGGp0oXBQMmeDGYX/u07V7fgoDB1OEkZqEraToJguc6wxQv1Arijx45slsW+y6lgAM9vkT+mjD6uxU9J4wcx/71zaONbQ3USc3l4pN+LiAjlfQEp5OA67wWcBvfeiF7ZVAf9NL2rMCVxNa93GJcWORwWLfGY442ZE8dN8U8nO8HuXDgY33AknG45YujnFVyV2JYuzof9o8Amimv9Cd3rSP1rqg9CZqFkwSfMTSRuXq73ZgtfPoGXZjOcYOBzRZ2qw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: cloudnative-pg
      name: cnpg-default-secret
      namespace: default
    type: kubernetes.io/basic-auth
