---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bento-pdf
  namespace: extras
  labels:
    app.kubernetes.io/name: bento-pdf
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  rules:
    - host: pdf.brhd.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: bento-pdf
                port:
                  number: 3000
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pdf.brhd.io
  namespace: extras
spec:
  endpoints:
    - dnsName: pdf.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
