# IMPORTANT: Creating multiple services for the same to bypass the 
# L2Advertisement limitations while using the externalTrafficPolicy = Local

# Load Balancer Service
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-lb-0
  namespace: default
  labels:
    app.kubernetes.io/name: blocky
  annotations:
    metallb.io/address-pool: dns-pool
    metallb.io/allow-shared-ip: "true"
    metallb.io/loadBalancerIPs: "192.168.1.220"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app.kubernetes.io/name: blocky
    apps.kubernetes.io/pod-index: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-lb-1
  namespace: default
  labels:
    app.kubernetes.io/name: blocky
  annotations:
    metallb.io/address-pool: dns-pool
    metallb.io/allow-shared-ip: "true"
    metallb.io/loadBalancerIPs: "192.168.1.221"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app.kubernetes.io/name: blocky
    apps.kubernetes.io/pod-index: "1"

# Ingress Service (DoH)
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-doh
  labels:
    app.kubernetes.io/name: blocky
spec:
  selector:
    app.kubernetes.io/name: blocky
  ports:
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
  type: ClusterIP