# Blocky API
---
apiVersion: v1
kind: Service
metadata:
  name: blocky
  labels:
    app.kubernetes.io/name: blocky
spec:
  selector:
    app.kubernetes.io/name: blocky
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
