apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - secret.yaml
  - vm-pod-scrape.yaml
  - vm-rule.yaml
helmCharts:
  - name: velero
    namespace: backup
    releaseName: velero
    version: 11.4.0
    repo: https://vmware-tanzu.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
