apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources: []
helmCharts:
  - name: velero
    namespace: backup
    releaseName: velero
    version: 11.4.0
    repo: https://vmware-tanzu.github.io/helm-charts
    # Leveraging `renovate` ability to detect updates in Helm values
    # Ref: https://docs.renovatebot.com/modules/manager/helm-values/
    valuesFile: values.yaml
