---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-secret
  namespace: backup
spec:
  encryptedData:
    rustfs: AgAhGeVNq/c5uPfyWy0208oDsp+r+n4OQLmdxoDLOltQ+hcfexbn9bdpjWlz4lnRFr42hAnhPOJ3HbBEc9lVWqAwOA2blgPsQREvyMOfMmnCPwbwPgTiDHRhjGhf6SkLcFNAj2LBdv1XGmhxTfLUBrlWKoNT8obaLKw/AEC673dupaXQH6CjYfUouc6M2Ce0gB2mD1Qd9rHh9vPaTWsScgCaUDUHNk59NczVXEF20q4NWsnwyKFS23xQKPJ5/rHeI33KxoL1xgYlqhK/9hikg+KL+WkJ4W0bx0EWKxDSjVrdCGrNRFdES796O4DcDunpjMK/lZw2rNM2ZZAfhrTjjppp0tE8D/g0AoRbkdKSyMtBVUH1uzqz4RlEVTfT0XLX3SbkFVxvMXNmqJk/apjLFJWG9lFrNRW/vBAA3hBYK2Blm0TUlZl3VbSBAHVY2tVOHSZXBcjhyqCBGTBBrzrUQCehOT/xqRNBzOIx0riYXjOO65FqNup3JI7r65iXjzo4/MUOU9j/mWLnuKEAd55QahCWvNd9qbe3yET2sdxjZf3Yhk0LbilX1KowjUsFPQOszor5eTC5OfDknD2tJ8M0owmgzyguk5nHBVcvCM0Ur8ohR+syhAC0J+95gwmDaHNB55r4vvFeEjX6LAogHcnUcRbhz7mfziybW2yLhlw9Sf13DPg6iMuhRg19v/+KLwKs/r5gP+l5xO99iqsxbUhAtWIG/evLR7ouYb615yU1jw3LTfo8ML7jqylQyOtqeEK2wHrkSPu80Gc78UYUZSyTMQlORo0t90Xb/8tIJUgafQrqFU2mYXDQGW7Lc/o4U20HtGaQqDvnfLXNpwIMwFH37n6O
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-secret
      namespace: backup
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-repo-credentials
  namespace: backup
spec:
  encryptedData:
    repository-password: AgCctM0PAF9tf7UZYprXwspM1MUZGuj5FULl6YXvye/4HUGeAKyTc7ZD2Icfzu5hCJqpA4OecQ78AA5LbiehM9ltTwpMCZKEVj8MnK+wEvnL5ZRcPhqiz7pk6tW/4HA3B1nNU1ZM9hR3iNNRvqZ8BkY60rg9TdIieW6nO2bdjCs7Fh5AR8kEFEwSl71cOh9S7EqPOFVIJvtD6rNXRtFH4NBmwJMvOs1rb9PRULzsvRtTvu8CbBAun77dSyposq3z/Jz3/+GdfMpI0MsqD7Mdkch9e2wIVpqapN/cw58RShMpmGnzDXUTnpVRh+PWEpxlmKQKAEtrNlVbMaXAVOUK82sKalhNmLNOjMjmmgG+nC0ZwIp85IaXAnQtsqpQDD8REkFMpytP9Tq2zGIlwFWxLoigS1FxB8i9hGGNwT16TWzHxZaIT4ns9EtgQ0teRv1+u9dNEOaqkybL6x4olsNI+pJEp77TJx8D1FTqKFlfTmCt36g+0Eyf+k9RDkwNPfUU/F/+TWYhMBCj4hvBP2HYzsk0Lp5RzYU9iO4Sp/DTnLGYjjtygva/Lfs1TPPrBx1+dRXIZPtNVqGHZESMGs/UmMxSe+2ye+V3h0581zE9N9n11Mb/4qML9etWSXvH1ya6eq9odGWMlf2Kb3Ye+yEN3TcjqQHmULPbc/fKFnMToVOldWh0AEhxB70moeOlNl7jX0AvtVHJNfYuHGzxnkEAGedtESU+fryEATykZr6EcNcd5smC6g==
  template:
    metadata:
      creationTimestamp: null
      name: velero-repo-credentials
      namespace: backup
    type: Opaque