---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  labels:
    app.kubernetes.io/instance: victoria-metrics
  name: velero-metrics
  namespace: backup
spec:
  podMetricsEndpoints:
    - port: http-monitoring
      scheme: http
      path: /metrics
      scrapeTimeout: 180s
      interval: 30s
      relabelConfigs:
        - target_label: job
          replacement: velero
  selector:
    matchLabels:
     app.kubernetes.io/name: velero