---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: rustfs.brhd.io
  namespace: rustfs
spec:
  endpoints:
    - dnsName: rustfs.brhd.io
      recordTTL: 86400
      recordType: CNAME
      targets:
        - casa.brhd.io
