---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rustfs
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgDa+Dmj+6sXjACIQyrO48gsK/rv+r7jmi+8E6Tj/FROsqWL9ZnSQqQ3QldneKFJgbPzOq0OOfvDcbsgxn2v4bpGDvt5W78VAwFTTEDwdqhM5OpAHSPCEogSBYb95561+oRn1ySv5ya/10iRncVQWW541D7vLzEh2v98jBrFBOnIEmYIEOtT3hsECKkfj74rcxr5Fec7w0S2vBSlikIjGgLQ8oBVQcfDahE9zP9ZGwti9c7aL6rDhD2LG5QxHKgIVDupBlu6OSxR6mYSR2UeHQQVKMTMtdHX1ioQaX4G7EbzFIBvoQ+nm0G9ImTlYMBMyrqRmGF+oztS9iVNXexXHcdQZErMm7tPLrR4lrCfirdPYWVMsTEixSwsgmpjy/Mgi0eLUhitzRpEDNJEjR95os4khgs3pBXz9Eix3S6I2ln54UERcZutdy/9upujctosNkexF8UYwpi9GSVibD3dHpmo6sTBbLQDTcBm608VjYZdZZYM3US1WzLr1qX+N/X5Zw0WX454QVf4DKqWnk1KrgHH7cq3kgEIZ5/wuYFlJu32F3jIIgW8PdptHJoRtqqmBkhg1XoKD4HZJX4ng3sMpjAz1/BiDPEGQDllAenPODU4GWKZIm1ZP3JXabJMzgwoDxQg9xoTwawWecolApVyDCqtPenVpRqAZg1CIz5Nhyd+YbXx1floD0oiYHczc+dGqqeC6yhRaQ==
    RUSTFS_SECRET_KEY: AgCrok4dWBHVii6stno2ppwQRLwxh/9mKDGtY9+24o5usqBIcVWECIq3HL90DC/tN243rapaPHM2ES9OoPkoD6RUa1ogIPmterrw9GeCoqvahFsx+tnWqWtKtSWcDdtDD1EcXWNomLrxgK3HJs4i3ZubCbtSvkkUZ+Cvjf3Ce5RT7EibPL72dkSBfTyXv4h509mN2AaWVkcuS5aMino46rjuA9DjSARyrC09Tt659ZRRbJWyKPteA98LadK9bjuFUXK7xi0dC4C4UrzF80CePSBZGG2avzqvMhoVRmb+wJLJ5qndZOHil+b0g0FeGNHP77MD7QCzIKHamsA0arkHWEXDN9nz25Q768hw7HDp31M9mSohBAiku8LUd//0iqOXzMcsXJEPDv0/7Y+FjTYUuYPjRC/HFD5tWl3PwLHKwp/j1k4LJ/k5Auc66jH/gcsLP8Rn8ptbop1teLn9dFi7r7Zy5cBJFtUb7KLqs4PScZd2TFsYTTjge8HV9rfl6k+Pjwnv2XNR8P3a2GataNgmxiZdPM4OX3uUQktS3pLcqbYlHd37F3skqqba+aUbFDJJZy1nXji+uZmqEOHBAEl28S9JzqkG0B+6qv52IxAVPfaJdkrQ4iYT6Og+dfJWh8olK23sqjlMoNOlyqbqNy61YpBbrCW/BP2rr2qXILcznxs4ChENj8LV6qbJqvUoABGkuJo7SpGwcbTuswD+sC+jg4cPo606ehgjsVBGJxhD
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: rustfs
      name: rustfs
      namespace: rustfs
    type: Opaque
